# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lidar_point.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lidar_point.proto',
  package='schema',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11lidar_point.proto\x12\x06schema\"\x95\x01\n\nLidarPoint\x12\x0c\n\x04time\x18\x05 \x01(\x01\x12\r\n\x05\x62\x65\x61ms\x18\x06 \x01(\r\x12\x0e\n\x06slices\x18\x07 \x01(\r\x12\x17\n\x0fvertical_angles\x18\x01 \x01(\x0c\x12\x19\n\x11horizontal_angles\x18\x02 \x01(\x0c\x12\x11\n\tdistances\x18\x03 \x01(\x0c\x12\x13\n\x0bintensities\x18\x04 \x01(\x0c\x62\x06proto3')
)




_LIDARPOINT = _descriptor.Descriptor(
  name='LidarPoint',
  full_name='schema.LidarPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='schema.LidarPoint.time', index=0,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beams', full_name='schema.LidarPoint.beams', index=1,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slices', full_name='schema.LidarPoint.slices', index=2,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertical_angles', full_name='schema.LidarPoint.vertical_angles', index=3,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='horizontal_angles', full_name='schema.LidarPoint.horizontal_angles', index=4,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distances', full_name='schema.LidarPoint.distances', index=5,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intensities', full_name='schema.LidarPoint.intensities', index=6,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=179,
)

DESCRIPTOR.message_types_by_name['LidarPoint'] = _LIDARPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LidarPoint = _reflection.GeneratedProtocolMessageType('LidarPoint', (_message.Message,), {
  'DESCRIPTOR' : _LIDARPOINT,
  '__module__' : 'lidar_point_pb2'
  # @@protoc_insertion_point(class_scope:schema.LidarPoint)
  })
_sym_db.RegisterMessage(LidarPoint)


# @@protoc_insertion_point(module_scope)
